---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cds-reload-lb-configuration-sa
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kube-system
  name: cds-reload-lb-configuration-role
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services/status
    verbs:
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - create
      - get
      - list
      - watch
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cds-reload-lb-configuration-role-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cds-reload-lb-configuration-cluster-role
subjects:
  - kind: ServiceAccount
    name: cds-reload-lb-configuration-sa
    namespace: kube-system

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reload-lb-config
  namespace: kube-system
data:
  reload-lb-config: |+
    [default]
    haproxy.refresh.period = 300
    nodePod.refresh.period = 30
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cds-reload-lb-configuration
  namespace: kube-system
spec:
  serviceName: reload-lb-svc
  replicas: 1
  selector:
    matchLabels:
      cds-app: cds-reload-lb-configuration
  template:
    metadata:
      labels:
        cds-app: cds-reload-lb-configuration
    spec:
      containers:
        - env:
            - name: CDS_OVERSEA
              valueFrom:
                configMapKeyRef:
                  name: cds-properties
                  key: oversea
            - name: DEPLOY_TYPE
              valueFrom:
                configMapKeyRef:
                  name: cds-properties
                  key: deploy_type
            - name: CDS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: cck-secrets
                  key: access_key_id
            - name: CDS_ACCESS_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: cck-secrets
                  key: access_key_secret
          image: registry-bj.capitalonline.net/test/cds-ha-configuration:v1.0
          name: cds-reload-lb-configuration
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /reload-lb/
              name: reload-lb-config
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.cck.net/infra
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: reload-lb-config
          name: reload-lb-config
